version: '3'
services:
  graphql-api:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graphql-api
    volumes:
      - ./data:/var/lib/postgresql/data